#Exploratory time series  
mega_list <- split.data.frame(dat_days_stockholm, as.factor(dat_days_stockholm$Municipality_Name))
sums <- means <- lapply(mega_list, "[", ,12) %>% lapply(sum)
means <- lapply(mega_list, "[", ,12) %>% lapply(mean)
means_dat <- as.data.frame(means)
means_dat <- t(means_dat)
colnames(means_dat) <- "average_number_fires"

mega_list_2$Botkyrka[12]%>% ts(frequency = 365)%>%auto.arima()
mega_list_2 [[1]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list_2 [[2]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[3]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[4]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[5]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[6]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[7]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list_2 [[8]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[9]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[10]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[11]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[12]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[13]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[14]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[15]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[16]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list_2 [[17]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list_2 [[18]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list_2 [[19]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list_2 [[20]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list_2 [[21]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list_2 [[22]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list_2 [[23]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list_2 [[24]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[25]] [12] %>% ts() %>% auto.arima()
mega_list_2 [[26]] [12] %>% ts(frequency = 365) %>% auto.arima()


mega_list_2 [[1]] [12] %>% ts(frequency = 365) %>% decompose() %>% plot()
mega_list_2 [[1]] [12] %>% ts(frequency = 365) %>% diff() %>% acf()

str(dat_days_stockholm)