require(tidyverse)
require(lubridate)
require(forecast)


#Exploratory time series  
mega_list <- split.data.frame(dat_days_stockholm, as.factor(dat_days_stockholm$Municipality_Name))
sums <- means <- lapply(mega_list, "[", ,12) %>% lapply(sum)
means <- lapply(mega_list, "[", ,12) %>% lapply(mean)
means_dat <- as.data.frame(means)
means_dat <- t(means_dat)
colnames(means_dat) <- "average_number_fires"

mega_list$Botkyrka[12]%>% ts(frequency = 365)%>%auto.arima()
mega_list [[1]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list [[2]] [12] %>% ts() %>% auto.arima()
mega_list [[3]] [12] %>% ts() %>% auto.arima()
mega_list [[4]] [12] %>% ts() %>% auto.arima()
mega_list [[5]] [12] %>% ts() %>% auto.arima()
mega_list [[6]] [12] %>% ts() %>% auto.arima()
mega_list [[7]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list [[8]] [12] %>% ts() %>% auto.arima()
mega_list [[9]] [12] %>% ts() %>% auto.arima()
mega_list [[10]] [12] %>% ts() %>% auto.arima()
mega_list [[11]] [12] %>% ts() %>% auto.arima()
mega_list [[12]] [12] %>% ts() %>% auto.arima()
mega_list [[13]] [12] %>% ts() %>% auto.arima()
mega_list [[14]] [12] %>% ts() %>% auto.arima()
mega_list [[15]] [12] %>% ts() %>% auto.arima()
mega_list [[16]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list [[17]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list [[18]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list [[19]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list [[20]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list [[21]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list [[22]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list [[23]] [12] %>% ts(frequency = 365) %>% auto.arima()
mega_list [[24]] [12] %>% ts() %>% auto.arima()
mega_list [[25]] [12] %>% ts() %>% auto.arima()
mega_list [[26]] [12] %>% ts(frequency = 365) %>% auto.arima()


mega_list [[1]] [12] %>% ts(frequency = 365) %>% decompose() %>% plot()
mega_list [[1]] [12] %>% ts(frequency = 365) %>% diff() %>% acf()

